language:
 - cpp

os:
 - linux
dist: trusty
sudo: required
compiler:
     - gcc
     - clang

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq unzip qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev libqt5webkit5-dev
 - sudo apt-get install -qq libcrypto++-utils libcrypto++-dev libfuse-dev
 - sudo apt-get install -qq libboost-thread-dev libboost-system-dev
 - sudo apt-get install -qq doxygen-latex
 - wget https://github.com/scross99/openp2p/archive/master.zip
 - unzip master.zip
 - mv openp2p-master ../openp2p && mkdir ../openp2p/build && cd ../openp2p/build && cmake .. && make && cd ../../p2pgroupchat

before_script:
 - mkdir build
 - cd build
 - cmake ..
script:
 - make
